name: recipe_app
description: Recipe App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.10.2"

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  logger: ^2.0.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  retrofit_generator: ^7.0.8
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
